default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  primary: &primary_production
    <<: *default
    database: todo_list_test_production
    username: todo_list_test
    password: <%= ENV['TODO_LIST_DATABASE_PASSWORD'] %>
  queue:
    <<: *primary_production
    database: todo_list_test_production
    username: todo_list_test
    password: <%= ENV['TODO_LIST_DATABASE_PASSWORD'] %>
    migrations_paths: db/queue_migrate
